name: Java Maven CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t shoaib1337/ci-cd-java-maven-app .
        docker tag shoaib1337/ci-cd-java-maven-app shoaib1337/ci-cd-java-maven-app:latest

    - name: Push Docker Image to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push shoaib1337/ci-cd-java-maven-app:latest
